### ISSUE TITLE
tag color is too dark!

### ISSUE THREAD

**Issue by hujie12306** [trey-wallis/obsidian-notion-like-tables#535]
### Describe the bug

tag color is too dark!  I can not read words.
![image](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/61086637/b8167cb2-595d-40a5-93c2-1851bb71a252)

### Steps to reproduce

When choose multi-tags

### Expected behavior

light color. 

### Are you using the mobile app?

No

### Obsidian debug info

no this option
![image](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/61086637/ad5c9d42-4373-4160-94f2-abb36bb65e73)

![image](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/61086637/bea764dd-2a96-4067-8b01-939b606ca5c7)

**Comment by trey-wallis** [comment]
@hujie12306 Which theme are you using?

**Comment by hujie12306** [comment]
> 您使用的是哪个主题？

![image](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/61086637/c7415a2a-3c7e-496f-a855-ab1455ced73f)
Blue Topaz

**Comment by trey-wallis** [comment]
@hujie12306 I cannot reproduce this in 6.18.0.

**Comment by highestpeak** [comment]
color dark can be solved by using Mysnippets plugin to change.  just add a snippet and add color like bellow to the snippet. finnaly enable it . problem solved!
``` css
.dataloom-light-gray--dark {
    background-color: #f12;
}
.dataloom-gray--dark {
    background-color: #f12;
}
.dataloom-brown--dark {
    background-color: #f12;
}
.dataloom-orange--dark {
    background-color: #f12;
}
.dataloom-yellow--dark {
    background-color: #f12;
}
.dataloom-green--dark {
    background-color: #f12;
}
.dataloom-blue--dark {
    background-color: #f12;
}
.dataloom-purple--dark {
    background-color: #f12;
}
.dataloom-pink--dark {
    background-color: #f12;
}
.dataloom-red--dark {
    background-color: #f12;
}
```
